--- arch/arm/mach-s5pv210/Makefile
+++ arch/arm/mach-s5pv210/Makefile
@@ -68,5 +68,6 @@
 obj-$(CONFIG_S5PV210_SETUP_FIMC1)	+= setup-fimc1.o
 obj-$(CONFIG_S5PV210_SETUP_FIMC2)	+= setup-fimc2.o
 
-obj-$(CONFIG_CPU_IDLE)		+= cpuidle.o didle.o
+obj-$(CONFIG_CPU_IDLE)		+= cpuidle.o
 obj-$(CONFIG_CPU_FREQ)		+= dev-cpufreq.o
+obj-$(CONFIG_CPU_DIDLE)		+= didle.o
